const products = [
  {
    id: "EGG-011",
    category: "Fishing",
    name: "23-Piece Fishing Emergency Kit",
    image: "assets/products/image8.jpeg",
    priceSar: 11.19,
    leadTimeDays: 7,
    deliveryDays: 67,
    description: "Compact emergency fishing kit with floats, hooks, bells, fishing line, straps, swivels, spinner blades, and small lure accessories.",
    details: ["23-piece accessory set", "Good for starter kits and travel fishing", "Compact add-on for outdoor retail bundles"],
    note: "Accessory details available on request."
  },
  {
    id: "EGG-023",
    category: "Boxing",
    name: "80 cm Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 23.85,
    leadTimeDays: 0,
    deliveryDays: 60,
    description: "Adult empty punching bag supplied with chain, screw hook, and safety buckle. Layered construction uses PU surface, cushioning, and soft impact protection.",
    details: ["80 cm height option", "Approx. 28 cm diameter", "Customer fills the bag locally"],
    note: ""
  },
  {
    id: "EGG-026",
    category: "Boxing",
    name: "80 cm Red & Black Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 26.22,
    leadTimeDays: 5,
    deliveryDays: 65,
    description: "Red and black empty boxing bag for combat training, taekwondo, and sanda practice. Includes chain, screw hook, and safety buckle.",
    details: ["Oxford cloth and PU build", "80 x 25 cm size", "Designed for customer filling"],
    note: "Carton packing surcharge applies when requested."
  },
  {
    id: "EGG-020",
    category: "Boxing",
    name: "80 cm Oxford Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 26.27,
    leadTimeDays: 0,
    deliveryDays: 60,
    description: "Oxford cloth empty punching bag with reinforced hanging hardware, zipper closure, screw fixing, and stable triangular strap support.",
    details: ["Approx. 0.8 kg per unit", "Includes thick chain and hanging accessories", "Easy-fill zipper closure"],
    note: "Approx. 0.8 kg per unit."
  },
  {
    id: "EGG-024",
    category: "Boxing",
    name: "1 m Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 33.56,
    leadTimeDays: 0,
    deliveryDays: 60,
    description: "Adult 1 m empty punching bag with PU surface, sponge and pearl-cotton cushioning layers, plus hanging chain and safety accessories.",
    details: ["100 cm height option", "Approx. 32 cm diameter", "Layered impact buffer construction"],
    note: ""
  },
  {
    id: "EGG-029",
    category: "Boxing",
    name: "1.6 m Inflatable Boxing Column",
    image: "assets/products/image22.png",
    priceSar: 33.73,
    leadTimeDays: 0,
    deliveryDays: 60,
    description: "Inflatable PVC boxing column for home fitness and recreational training. Lightweight retail-friendly item with compact carton dimensions.",
    details: ["160 x 60 x 30 cm", "PVC material", "Approx. 0.68 kg per unit"],
    note: ""
  },
  {
    id: "EGG-027",
    category: "Boxing",
    name: "1 m Red & Black Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 34.22,
    leadTimeDays: 5,
    deliveryDays: 65,
    description: "Red and black 1 m empty punching bag for boxing, taekwondo, and sanda. Supplied with chain, screw hook, and safety buckle.",
    details: ["Oxford cloth and PU material", "100 x 30 cm size", "Customer fills the bag locally"],
    note: ""
  },
  {
    id: "EGG-021",
    category: "Boxing",
    name: "1 m Oxford Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 37.95,
    leadTimeDays: 0,
    deliveryDays: 60,
    description: "Oxford cloth 1 m punching bag with reinforced hanging chain, zipper fill opening, and durable screw-mounted hardware.",
    details: ["Approx. 0.9 kg per unit", "Includes thick chain and accessories", "Suitable for home fitness training"],
    note: "Approx. 0.9 kg per unit."
  },
  {
    id: "EGG-041",
    category: "Fishing",
    name: "Red Sea Fishing Rod Kit",
    image: "assets/products/image31.png",
    priceSar: 38.07,
    leadTimeDays: 15,
    deliveryDays: 75,
    description: "Export sea fishing rod kit with fiberglass rod, red reel, line, and accessory set for beginner and casual fishing bundles.",
    details: ["1.8 m fiberglass rod", "Includes 200-size red reel", "Includes 20 accessories"],
    note: ""
  },
  {
    id: "EGG-042",
    category: "Fishing",
    name: "Green Sea Fishing Rod Kit",
    image: "assets/products/image31.png",
    priceSar: 38.07,
    leadTimeDays: 15,
    deliveryDays: 75,
    description: "Green sea fishing rod kit with fiberglass rod, reel, fishing line, and compact accessory bundle for export retail programs.",
    details: ["1.8 m fiberglass rod", "Includes 200-size green reel", "Includes fish, float, and net accessories"],
    note: ""
  },
  {
    id: "EGG-043",
    category: "Fishing",
    name: "Blue Sea Fishing Rod Kit",
    image: "assets/products/image31.png",
    priceSar: 38.07,
    leadTimeDays: 15,
    deliveryDays: 75,
    description: "Blue sea fishing rod kit for outdoor retail assortments, supplied with fiberglass rod, reel, line, and essential accessories.",
    details: ["1.8 m fiberglass rod", "Includes 200-size blue reel", "Ready for starter fishing bundles"],
    note: ""
  },
  {
    id: "EGG-050",
    category: "Boxing",
    name: "60 cm Black Hanging Punching Bag Set",
    image: "assets/products/display-black-bag-set-60.png",
    priceSar: 39.33,
    leadTimeDays: 3,
    deliveryDays: 63,
    description: "Black 60 cm empty hanging punching bag made from Oxford cloth and supplied with an accessory bundle for entry-level boxing practice.",
    details: ["25 cm diameter", "Includes chain, hook, gloves, wraps, and guards", "Buy-one-get-eight accessory set"],
    note: ""
  },
  {
    id: "EGG-025",
    category: "Boxing",
    name: "1.2 m Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 42.22,
    leadTimeDays: 0,
    deliveryDays: 60,
    description: "Adult 1.2 m empty punching bag with layered PU, sponge, and pearl-cotton structure for durable impact training.",
    details: ["120 cm height option", "Approx. 37 cm diameter", "Includes chain, screw hook, and safety buckle"],
    note: ""
  },
  {
    id: "EGG-022",
    category: "Boxing",
    name: "1.2 m Oxford Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 44.89,
    leadTimeDays: 0,
    deliveryDays: 60,
    description: "Oxford cloth 1.2 m empty punching bag with reinforced chain, zipper fill opening, screw-mounted hardware, and stable triangular strap support.",
    details: ["Designed for customer filling", "Includes heavy-duty hanging accessories", "Home or light gym training use"],
    note: ""
  },
  {
    id: "EGG-028",
    category: "Boxing",
    name: "1.2 m Red & Black Empty Punching Bag",
    image: "assets/products/display-punching-bag-red.jpeg",
    priceSar: 46.89,
    leadTimeDays: 5,
    deliveryDays: 65,
    description: "Red and black 1.2 m empty punching bag with PU trim, suitable for boxing, taekwondo, and sanda training assortments.",
    details: ["120 x 37 cm size", "Oxford cloth with black PU trim", "Includes chain, screw hook, and safety buckle"],
    note: ""
  },
  {
    id: "EGG-051",
    category: "Boxing",
    name: "80 cm Black Hanging Punching Bag Set",
    image: "assets/products/display-black-bag-set-80.png",
    priceSar: 47.77,
    leadTimeDays: 3,
    deliveryDays: 63,
    description: "Black 80 cm hanging punching bag set with Oxford cloth bag and accessory bundle for beginner boxing retail kits.",
    details: ["28 cm diameter", "Includes chain, hook, gloves, wraps, and guards", "Buy-one-get-eight accessory set"],
    note: ""
  },
  {
    id: "EGG-052",
    category: "Boxing",
    name: "100 cm Black Hanging Punching Bag Set",
    image: "assets/products/display-black-bag-set-100.png",
    priceSar: 60.66,
    leadTimeDays: 3,
    deliveryDays: 63,
    description: "Black 100 cm empty hanging punching bag with Oxford cloth shell and complete accessory bundle for customer-ready boxing kits.",
    details: ["30 cm diameter", "Includes safety buckle and dedicated chain", "Buy-one-get-eight accessory set"],
    note: "100 cm black empty bag version."
  },
  {
    id: "EGG-054",
    category: "Boxing",
    name: "80 cm Black PU Punching Bag Accessory Set",
    image: "assets/products/display-punching-bag-black.png",
    priceSar: 63,
    leadTimeDays: 3,
    deliveryDays: 63,
    description: "Black 80 cm adult empty punching bag made with PU leather and supplied with a broad accessory kit for boxed retail sales.",
    details: ["25 cm diameter", "Includes chain, gloves, wraps, hand guards, wrist guards, foot guards, and mounting plate", "80 cm black length"],
    note: ""
  },
  {
    id: "EGG-053",
    category: "Boxing",
    name: "120 cm Black Hanging Punching Bag Set",
    image: "assets/products/display-black-bag-set-120.png",
    priceSar: 69.54,
    leadTimeDays: 3,
    deliveryDays: 63,
    description: "Black 120 cm hanging empty punching bag with Oxford cloth shell and included hardware and boxing accessories.",
    details: ["32 cm diameter", "Includes chain, hook, gloves, wraps, and guards", "Buy-one-get-eight accessory set"],
    note: ""
  },
  {
    id: "EGG-055",
    category: "Boxing",
    name: "100 cm Black PU Punching Bag Accessory Set",
    image: "assets/products/display-punching-bag-black.png",
    priceSar: 72.27,
    leadTimeDays: 3,
    deliveryDays: 63,
    description: "Black 100 cm adult empty punching bag with PU leather shell and complete accessory bundle for home boxing setups.",
    details: ["30 cm diameter", "Includes mounting hardware and boxing accessories", "100 cm black length"],
    note: ""
  },
  {
    id: "EGG-056",
    category: "Boxing",
    name: "120 cm Black PU Punching Bag Accessory Set",
    image: "assets/products/display-punching-bag-black.png",
    priceSar: 77.83,
    leadTimeDays: 3,
    deliveryDays: 63,
    description: "Black 120 cm adult empty punching bag with PU leather shell, reinforced mounting hardware, and a full accessory set.",
    details: ["35 cm diameter", "Includes chain, gloves, wraps, guards, screws, and mounting plate", "120 cm black length"],
    note: ""
  },
  {
    id: "EGG-012",
    category: "Fishing",
    name: "2.1 m Fishing Rod Bag Set",
    image: "assets/products/image16.jpeg",
    priceSar: 90.93,
    leadTimeDays: 7,
    deliveryDays: 67,
    description: "2.1 m fishing rod bag set with sea rod, reel, fishing line, soft lures, minnows, spinner blades, and jig heads.",
    details: ["2.1 m rod and RC1000 or PC1000 reel options", "Includes fishing bag", "Blue or red rod set options"],
    note: "Color and reel combinations available."
  },
  {
    id: "EGG-002",
    category: "Fitness",
    name: "Adjustable Barbell Rack",
    image: "assets/products/image5.jpeg",
    priceSar: 84.31,
    leadTimeDays: 45,
    deliveryDays: 105,
    description: "Multi-function adjustable barbell rack built from steel with five-position height and width adjustment for home training.",
    details: ["102 x 45 x 121 cm expanded size", "150 kg load capacity", "Stable anti-tip structure"],
    note: ""
  },
  {
    id: "EGG-003",
    category: "Fitness",
    name: "Foldable Multi-Function Dumbbell Bench",
    image: "assets/products/image7.jpeg",
    priceSar: 153.23,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Upgraded foldable dumbbell bench with a reinforced triangular frame and thicker, wider pad for comfortable home strength training.",
    details: ["Steel, foam, and PU leather", "118 x 52 x 26 cm", "For shaping, muscle training, and home fitness"],
    note: "Multiple specification levels available."
  },
  {
    id: "EGG-004",
    category: "Fitness",
    name: "3-in-1 Foldable Dumbbell Bench",
    image: "assets/products/image2.jpeg",
    priceSar: 168.23,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "3-in-1 foldable dumbbell bench with reinforced triangular frame, wider pad, adjustable headrest, and assisted pull ropes.",
    details: ["Steel, foam, and PU leather", "118 x 52 x 26 cm", "Foldable home gym bench"],
    note: "Multiple specification levels available."
  },
  {
    id: "EGG-005",
    category: "Rowing",
    name: "Quiet Hydraulic Rowing Machine",
    image: "assets/products/image9.jpeg",
    priceSar: 206.07,
    leadTimeDays: 25,
    deliveryDays: 85,
    description: "Home hydraulic rowing machine in black or white with foldable body, adjustable seat height, and 12 resistance levels.",
    details: ["Iron and PP construction", "Optional backrest support", "CE and RoHS compliant accessories"],
    note: "Backrest support option available with surcharge."
  },
  {
    id: "EGG-001",
    category: "Fitness",
    name: "6206 Multi-Function Pull-Up & Dip Station",
    image: "assets/products/image4.jpeg",
    priceSar: 214.22,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Free-standing pull-up and dip station for home training, covering pull-ups, leg raises, dips, push-ups, stretching, and core workouts.",
    details: ["2300 x 750 x 900 mm expanded size", "1.2 mm thickened steel tube", "150 kg load capacity"],
    note: "No wall drilling required."
  },
  {
    id: "EGG-040",
    category: "Fitness",
    name: "Heavy-Duty Pull-Up & Dip Station with Backrest",
    image: "assets/products/image30.png",
    priceSar: 227.42,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Upgraded free-standing pull-up station with backrest, arm pads, rings, triple support frame, and wide anti-tip base.",
    details: ["100 x 85 x 240 cm", "Adjustable height up to 2.4 m", "Black and red steel frame"],
    note: "Heavy-duty flagship style."
  },
  {
    id: "EGG-006",
    category: "Rowing",
    name: "SH-X01 Single-Rail Rowing Machine",
    image: "assets/products/image12.png",
    priceSar: 248.31,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "SH-X01 single-rail rowing machine for home fitness, supplied in grey or silver with steel tube and ABS construction.",
    details: ["Single-rail rowing design", "Steel tube and ABS", "Packed with PE bag and carton"],
    note: ""
  },
  {
    id: "EGG-007",
    category: "Rowing",
    name: "SH-X02 Single-Rail Rowing Machine",
    image: "assets/products/image11.png",
    priceSar: 257.17,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "SH-X02 single-rail rowing machine with symmetrical 12-level hydraulic resistance and digital training data display.",
    details: ["Displays time and distance", "Steel tube and ABS", "Packed with PE bag and carton"],
    note: ""
  },
  {
    id: "EGG-008",
    category: "Rowing",
    name: "SH-X03 Dual-Paddle Hydraulic Rowing Machine",
    image: "assets/products/image13.png",
    priceSar: 283.53,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Black dual-paddle hydraulic rowing machine with LCD display, anti-slip rubber base, quiet hydraulic rods, and widened comfort seat.",
    details: ["120 kg load range", "Hydraulic resistance", "Electroplated rowing handles"],
    note: ""
  },
  {
    id: "EGG-009",
    category: "Rowing",
    name: "SH-X04 Hydraulic Rowing Machine",
    image: "assets/products/image14.png",
    priceSar: 285.55,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "SH-X04 hydraulic rowing machine without backrest, available in grey or black for compact home cardio assortments.",
    details: ["Steel tube and ABS", "No-backrest model", "Packed with PE bag and carton"],
    note: ""
  },
  {
    id: "EGG-010",
    category: "Rowing",
    name: "SH-X05 Hydraulic Rowing Machine with Backrest",
    image: "assets/products/image15.png",
    priceSar: 300.55,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "SH-X05 hydraulic rowing machine with backrest, available in grey or black with steel tube and ABS structure.",
    details: ["Backrest model", "Steel tube and ABS", "Packed with PE bag and carton"],
    note: ""
  },
  {
    id: "EGG-013",
    category: "Trampolines",
    name: "8 ft Classic Outdoor Trampoline",
    image: "assets/products/image3.jpeg",
    priceSar: 399.56,
    leadTimeDays: 15,
    deliveryDays: 75,
    description: "8 ft classic outdoor trampoline with safety enclosure, PP jumping mat, thickened galvanized steel tube frame, and PE net.",
    details: ["Classic safety-net design", "Blue or orange color options", "5, 6, 8, 10, 12, 14, and 16 ft sizes available"],
    note: "Additional size options available."
  },
  {
    id: "EGG-016",
    category: "Trampolines",
    name: "8 ft Lantern-Style Trampoline with Ladder",
    image: "assets/products/image17.jpeg",
    priceSar: 442.55,
    leadTimeDays: 20,
    deliveryDays: 80,
    description: "8 ft lantern-style outdoor trampoline with safety net, PP jumping mat, thickened galvanized steel tube frame, PE net, and ladder.",
    details: ["Includes ladder", "Safety enclosure included", "Outdoor family recreation item"],
    note: "Ladder included."
  },
  {
    id: "EGG-047",
    category: "Trampolines",
    name: "8 ft Classic Trampoline - 2.44 m",
    image: "assets/products/image33.png",
    priceSar: 456.05,
    leadTimeDays: 40,
    deliveryDays: 100,
    description: "8 ft blue classic outdoor trampoline with safety net, spring structure, and thickened galvanized steel tube frame.",
    details: ["2.44 m diameter", "2 m overall height", "Suitable for 4 to 5 users"],
    note: "Classic 1 style."
  },
  {
    id: "EGG-014",
    category: "Trampolines",
    name: "10 ft Classic Outdoor Trampoline",
    image: "assets/products/image1.jpeg",
    priceSar: 529.02,
    leadTimeDays: 16,
    deliveryDays: 76,
    description: "10 ft classic outdoor trampoline with safety enclosure, PP jumping mat, thickened galvanized steel tube frame, and PE net.",
    details: ["Classic round trampoline", "Safety net included", "Outdoor family recreation item"],
    note: ""
  },
  {
    id: "EGG-019",
    category: "E-Mobility",
    name: "M365 Folding Electric Scooter",
    image: "assets/products/image20.jpeg",
    priceSar: 537.96,
    leadTimeDays: 10,
    deliveryDays: 70,
    description: "Portable M365-style folding electric scooter for adults with aluminum alloy frame, 10-inch profile, and two-wheel commuting setup.",
    details: ["Max speed 30 km/h", "Approx. 30 km range", "8.5-inch honeycomb tires"],
    note: "Black and white options available."
  },
  {
    id: "EGG-017",
    category: "Trampolines",
    name: "10 ft Lantern-Style Trampoline with Ladder",
    image: "assets/products/image18.jpeg",
    priceSar: 561.64,
    leadTimeDays: 20,
    deliveryDays: 80,
    description: "10 ft lantern-style outdoor trampoline with safety enclosure, PP jumping mat, galvanized steel tube frame, PE net, and ladder.",
    details: ["Includes ladder", "Safety net included", "Outdoor family recreation item"],
    note: "Ladder included."
  },
  {
    id: "EGG-044",
    category: "Trampolines",
    name: "8 ft Lantern-Style Trampoline 7123",
    image: "assets/products/image32.png",
    priceSar: 567.32,
    leadTimeDays: 40,
    deliveryDays: 100,
    description: "7123 8 ft lantern-style trampoline with safety net, thickened hot-dip galvanized tube frame, and heavy-duty spring wire.",
    details: ["2.44 m diameter", "15 mm wall-thickness tube", "Without basketball board"],
    note: ""
  },
  {
    id: "EGG-048",
    category: "Trampolines",
    name: "10 ft Classic Trampoline - 3.05 m",
    image: "assets/products/image34.png",
    priceSar: 574.83,
    leadTimeDays: 40,
    deliveryDays: 100,
    description: "10 ft blue classic outdoor trampoline with safety net, spring structure, PP jumping mat, and thickened galvanized steel frame.",
    details: ["3.05 m diameter", "2.54 m overall height", "Suitable for 5 to 6 users"],
    note: "Classic 1 style."
  },
  {
    id: "EGG-015",
    category: "Trampolines",
    name: "12 ft Classic Outdoor Trampoline",
    image: "assets/products/image6.jpeg",
    priceSar: 642.66,
    leadTimeDays: 17,
    deliveryDays: 77,
    description: "12 ft classic outdoor trampoline with safety enclosure, PP jumping mat, thickened galvanized steel tube frame, and PE net.",
    details: ["Classic round trampoline", "Safety net included", "Outdoor family recreation item"],
    note: ""
  },
  {
    id: "EGG-018",
    category: "Trampolines",
    name: "12 ft Lantern-Style Trampoline with Ladder",
    image: "assets/products/image19.jpeg",
    priceSar: 673.38,
    leadTimeDays: 20,
    deliveryDays: 80,
    description: "12 ft lantern-style outdoor trampoline with safety enclosure, PP jumping mat, galvanized steel frame, PE net, and ladder.",
    details: ["Includes ladder", "Safety net included", "Large outdoor family model"],
    note: "Ladder included."
  },
  {
    id: "EGG-045",
    category: "Trampolines",
    name: "10 ft Lantern-Style Trampoline 7123",
    image: "assets/products/image32.png",
    priceSar: 679.29,
    leadTimeDays: 40,
    deliveryDays: 100,
    description: "7123 10 ft lantern-style trampoline with safety net, thickened hot-dip galvanized frame, and reinforced spring wire.",
    details: ["3.05 m diameter", "15 mm wall-thickness tube", "Without basketball board"],
    note: ""
  },
  {
    id: "EGG-049",
    category: "Trampolines",
    name: "12 ft Classic Trampoline - 3.66 m",
    image: "assets/products/image35.png",
    priceSar: 697.59,
    leadTimeDays: 40,
    deliveryDays: 100,
    description: "12 ft blue classic outdoor trampoline with safety enclosure, PP jumping mat, galvanized tube frame, and PE net.",
    details: ["3.66 m diameter", "2.6 m overall height", "Suitable for 8 to 10 users"],
    note: "Classic 1 style."
  },
  {
    id: "EGG-046",
    category: "Trampolines",
    name: "12 ft Lantern-Style Trampoline 7123",
    image: "assets/products/image32.png",
    priceSar: 833.61,
    leadTimeDays: 40,
    deliveryDays: 100,
    description: "7123 12 ft lantern-style trampoline with safety net, thickened hot-dip galvanized frame, and reinforced spring wire.",
    details: ["3.66 m diameter", "15 mm wall-thickness tube", "Without basketball board"],
    note: ""
  },
  {
    id: "EGG-038",
    category: "Fitness",
    name: "Single-Side Cable Crossover Trainer - 70 kg",
    image: "assets/products/image29.png",
    priceSar: 851.3,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Single-side cable crossover trainer with 70 kg weight stack, steel frame, wide foot platform, and stable tripod-style base.",
    details: ["85 cm upper width, 106 cm lower width", "215 cm height", "5 to 100 kg adjustable training range"],
    note: ""
  },
  {
    id: "EGG-039",
    category: "Fitness",
    name: "Single-Side Cable Crossover Trainer - 100 kg",
    image: "assets/products/image29.png",
    priceSar: 995.75,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Single-side cable crossover trainer with 100 kg weight stack, steel frame, wide foot platform, and stable tripod-style base.",
    details: ["85 cm upper width, 106 cm lower width", "215 cm height", "5 to 100 kg adjustable training range"],
    note: ""
  },
  {
    id: "EGG-034",
    category: "E-Mobility",
    name: "MZ-24 Electric Bike 350W",
    image: "assets/products/image10.png",
    priceSar: 1476.69,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Custom MZ-24 electric bike with high-carbon steel frame, 26-inch tires, mechanical disc brakes, front and rear suspension, and Shimano 7-speed system.",
    details: ["350W motor", "36V 10.4Ah battery", "Approx. 45 km range"],
    note: "Charging time: 5 to 6 hours."
  },
  {
    id: "EGG-035",
    category: "E-Mobility",
    name: "26-Inch Mountain Electric Bike 500W",
    image: "assets/products/image25.png",
    priceSar: 1723.31,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Custom 26-inch mountain electric bike with high-carbon steel frame, mechanical disc brakes, front and rear suspension, and Shimano 7-speed system.",
    details: ["500W motor", "36V 10.4Ah battery", "Approx. 50 km range"],
    note: "Charging time: 5 to 6 hours."
  },
  {
    id: "EGG-036",
    category: "E-Mobility",
    name: "20-Inch Touring Electric Moped 500W",
    image: "assets/products/image27.png",
    priceSar: 1784.58,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Custom touring electric moped with high-carbon steel frame, 20-inch tires, 500W motor, mechanical disc brakes, and front fork suspension.",
    details: ["48V battery platform", "Approx. 60 km range", "Max speed 45 km/h"],
    note: "Charging time: 5 to 6 hours."
  },
  {
    id: "EGG-033",
    category: "E-Mobility",
    name: "20-Inch Fat Tire Off-Road E-Bike",
    image: "assets/products/image26.png",
    priceSar: 1862.84,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Custom 20-inch fat tire off-road e-bike with high-speed brushless geared motor, Shimano 7-speed drivetrain, color LED display, and removable lithium battery.",
    details: ["500W rated motor, 750W peak", "48V 15Ah battery", "Max speed 50 km/h"],
    note: "Front and rear disc brakes with dual suspension."
  },
  {
    id: "EGG-032",
    category: "E-Mobility",
    name: "Panther Fat-Tire E-Bike",
    image: "assets/products/image24.jpeg",
    priceSar: 1922.94,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Panther fat-tire e-bike with iron frame, Shimano 7-speed system, 20 x 4.0 inch tires, front and rear disc brakes, and waterproof wiring.",
    details: ["500W high-speed motor", "Electric-only range around 40 km", "Max speed 40 km/h"],
    note: "Vehicle size: 1700 x 740 x 1100 mm."
  },
  {
    id: "EGG-037",
    category: "Fitness",
    name: "Multi-Function Weight Bench & Squat Rack Set",
    image: "assets/products/image28.png",
    priceSar: 2202.25,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Black home strength training set combining weight bench, squat rack, barbell rack, bench press station, and folding storage design.",
    details: ["Expanded size: 161 x 138 x 106 cm", "Folded size: 138 x 69.5 x 154.5 cm", "Home gym strength-training bundle"],
    note: "Black version."
  },
  {
    id: "EGG-030",
    category: "E-Mobility",
    name: "48V 500W Alloy Electric Bike",
    image: "assets/products/image23.jpeg",
    priceSar: 3135.84,
    leadTimeDays: 25,
    deliveryDays: 85,
    description: "Aluminum alloy electric bike with electric and pedal-assist modes, Shimano 7-speed drivetrain, disc brakes, and P1 LCD display.",
    details: ["48V 500W motor", "48V 12Ah domestic battery", "30 to 35 km range"],
    note: "Charging time: 4 to 5 hours."
  },
  {
    id: "EGG-031",
    category: "E-Mobility",
    name: "48V 750W Alloy Electric Bike",
    image: "assets/products/image23.jpeg",
    priceSar: 3205.28,
    leadTimeDays: 30,
    deliveryDays: 90,
    description: "Aluminum alloy electric bike with stronger 750W motor, electric and pedal-assist modes, Shimano 7-speed drivetrain, disc brakes, and P1 LCD display.",
    details: ["48V 750W motor", "48V 12Ah domestic battery", "30 to 35 km range"],
    note: "Charging time: 4 to 5 hours."
  }
];

window.EGG_PRODUCTS = products;
